name: Firmware Image Build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build complitation container
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: docker build -t esp32-micropython-image-build-$IMAGE_TAG .

    - name: Build firmware image in complitation container
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: docker run -v /workspace/output:/data/micropython/ports/esp32/build-GENERIC/ esp32-micropython-image-build-$IMAGE_TAG

    - name: check /workspace/output directory
      run: ls -lah /workspace/output
